**not logical operator**

In [1]:
x = True

In [2]:
y = not x

In [3]:
y

False

In [7]:
v = [23,345,56,67,4]

In [14]:
x = [not i for i in v]

In [15]:
x

[False, False, False, False, False]

by using the not we can reverse the output of the Python.

**Swappig the variable**

In [4]:
a = 100
b=200

In [5]:
a,b = b,a

In [6]:
print(a)
print(b)

200
100


**Binary operator**

- Compliment(~)
- and (&)
- or  (|)
- xor (^)
- left shift (<<)
- Right shift (>>)

- Compliment Operator.

It help us to reverse an operation.

In [19]:
~1

-2

In [20]:
~0

-1

#### Result

In [1]:
x = input('enter a string  :')

enter a string  :Harish


In [5]:
result = eval(input('enter an expression  :' ))
print(result)

enter an expression  :88+2
90


**While Loop**

- Counter initializer
- Specify the condition
- and gives increment or decrement.

#### Break Statement

In [2]:
x = int(input('How many candy you want :-'))

i = 0

while i<=x:
    print('Candy')
    i=i+1
    
print()
print('Bye')

How many candy you want :-3
Candy
Candy
Candy
Candy

Bye


In [3]:
x = int(input('How many candy you want :-'))

i = 0
av=5
while i<=x:
    if x>av:
        print('Out of the stock')
        break
        
    print('Candy')
    i=i+1
    
print()
print('Bye')

How many candy you want :-7
Out of the stock

Bye


#### Continue Statement

In [12]:
for i in range(10):
    if (i%3==0) | (i%2==0):   #ignore the two  things
        continue
    print(i)

1
5
7


#### Pass

In [11]:
for i in range(10):
    if (i%3==0) | (i%2==0):  #its performing beacause use pass means the contion not implemented on the print() function.
        pass
    print(i)

0
1
2
3
4
5
6
7
8
9


#### Array

In [69]:
from array import array

Arrray conatins only same type of dtyeps

In [70]:
arr = array('i',[23,454,56,77,88,98]) #we need define evrytime what kind of dtype we are going to use.

In [71]:
arr

array('i', [23, 454, 56, 77, 88, 98])

In [72]:
arr[0]=0.2   #so if we try to append something which having diffrent dtype that time it will not allow to do that.

TypeError: integer argument expected, got float

In [73]:
address,size=arr.buffer_info()

In [74]:
address,size

(106735904, 6)

In [75]:
for i in arr:
    print(i)

23
454
56
77
88
98


In [76]:
val=arr.typecode

In [77]:
new_array = array(val,(i*i for i in arr))

In [78]:
new_array

array('i', [529, 206116, 3136, 5929, 7744, 9604])

### Multi-dimensional Array

In [80]:
import numpy as np

- Array
- Linespace
- Flatten
- Arange
- Zeros
- Once
- Logspace

In [81]:
arr = np.array([1,2,4,56,77,23,12,566,88,656,234])

In [82]:
arr

array([  1,   2,   4,  56,  77,  23,  12, 566,  88, 656, 234])

In [83]:
for i in arr:
    print(i)

1
2
4
56
77
23
12
566
88
656
234


- It consisting the only type of the integer if we want the add the any float kind of dtype then iyt will make all the dtypes in float.

In [87]:
arr[0]=0.1

In [88]:
arr

array([  0,   2,   4,  56,  77,  23,  12, 566,  88, 656, 234])

In [89]:
arr.tolist()

[0, 2, 4, 56, 77, 23, 12, 566, 88, 656, 234]

In [91]:
arr.argmax()

9

In [92]:
arr.argmin()

0

In [95]:
c=arr.argsort()
c

array([ 0,  1,  2,  6,  5,  3,  4,  8, 10,  7,  9], dtype=int32)

In [96]:
arr[c]

array([  0,   2,   4,  12,  23,  56,  77,  88, 234, 566, 656])

In [106]:
numpy_array = np.array([1,2,3,5,534,667,88,997,44,2211,124,56,77,843],float)

In [108]:
numpy_array #now see

array([1.000e+00, 2.000e+00, 3.000e+00, 5.000e+00, 5.340e+02, 6.670e+02,
       8.800e+01, 9.970e+02, 4.400e+01, 2.211e+03, 1.240e+02, 5.600e+01,
       7.700e+01, 8.430e+02])

In [112]:
linespa = np.linspace(1,20,20)
linespa

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [115]:
arange=np.arange(2,10,2)

In [116]:
arange

array([2, 4, 6, 8])

In [118]:
num_zero=np.zeros([3,3])
num_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [120]:
num_zero.ndim

2

In [122]:
num_zero1 = num_zero

In [124]:
num_zero.dot(num_zero1)  #muplication of an array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [125]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [130]:
mat = np.array([[2234,34,244],[22,90,72],[44,22,90]])

In [131]:
mat

array([[2234,   34,  244],
       [  22,   90,   72],
       [  44,   22,   90]])

In [133]:
mat.ndim

2

In [134]:
mat.flatten()

array([2234,   34,  244,   22,   90,   72,   44,   22,   90])

In [135]:
mat.transpose()

array([[2234,   22,   44],
       [  34,   90,   22],
       [ 244,   72,   90]])

In [136]:
np.max(mat)

2234

In [137]:
np.min(mat)

22

In [143]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [144]:
mat1 = mat+5

In [145]:
mat1

array([[2239,   39,  249],
       [  27,   95,   77],
       [  49,   27,   95]])

In [146]:
mat3 = mat+mat1

In [148]:
mat3   #elementwise adding here happening

array([[4473,   73,  493],
       [  49,  185,  149],
       [  93,   49,  185]])

- In the numpy and mat module we have lot of things to do with an array.

- Coonatenate

In [150]:
array3 =np.concatenate([mat3,mat],axis=1)

In [151]:
array3

array([[4473,   73,  493, 2234,   34,  244],
       [  49,  185,  149,   22,   90,   72],
       [  93,   49,  185,   44,   22,   90]])

In [152]:
array4 =np.concatenate([mat3,mat],axis=0)

In [153]:
array4

array([[4473,   73,  493],
       [  49,  185,  149],
       [  93,   49,  185],
       [2234,   34,  244],
       [  22,   90,   72],
       [  44,   22,   90]])

In [154]:
np.vstack([mat3,mat])

array([[4473,   73,  493],
       [  49,  185,  149],
       [  93,   49,  185],
       [2234,   34,  244],
       [  22,   90,   72],
       [  44,   22,   90]])

In [155]:
np.hstack([mat3,mat])

array([[4473,   73,  493, 2234,   34,  244],
       [  49,  185,  149,   22,   90,   72],
       [  93,   49,  185,   44,   22,   90]])

**call by value call by address.**

In [156]:
array = [23,45,65,24]

In [157]:
arra1 = array

In [159]:
print(array)
print(arra1)

[23, 45, 65, 24]
[23, 45, 65, 24]


In [162]:
print(id(array))    #They both have the same address we can say the both are the same array it effect on each other if we made any changes
print(id(arra1))

219736544
219736544


#### Shallow copy()

In [163]:
arra1 = array

#### Hard Copy()

In [164]:
arra1 = array.copy()

In [165]:
print(id(arra1))
print(id(array))

219957888
219736544


- Since they having the diffrent address that means they not same.

In [166]:
mat.shape

(3, 3)

**Operation on arrays**

In [176]:
arrays = np.array([
      
        [223,556,67,23,1343,1343,233,455,34],
        [44,545,656,23,12334,545,332,11,55]
    
    
])

In [177]:
arrays.shape

(2, 9)

In [178]:
arrays.ndim

2

In [183]:
ar=arrays.reshape(3,3,2)

- 3 -  three represent Three dimensional array big() that we have got
- 3 -   three represent the Three dimensional we will get indivisually
- 2 - Inside that 3 dim arrays we will get the two values

In [184]:
ar

array([[[  223,   556],
        [   67,    23],
        [ 1343,  1343]],

       [[  233,   455],
        [   34,    44],
        [  545,   656]],

       [[   23, 12334],
        [  545,   332],
        [   11,    55]]])

In [185]:
ar.shape

(3, 3, 2)

In [186]:
ar.ndim

3

### Scope of the Global and Local Variable.

**We should have an idea about the scope of gloabal and local variable while working on the functions.**

In [189]:
a = 33

def function():
    a=10
    
    print(a)


print(a)

33


- we can see we only accesing the global variable that is 33.

In [190]:
a = 33

def function():
    a=10
    
    print(a)
function()

print(a)

10
33


- If we will call the function in this case we had are able both local and global variable.

- If we want specify that the loacal vaiable is not local it's Global for that we need use the keyworld that **global.**

In [191]:
a = 33

def function():
    global a
    a=10
    
    print(a)
function()

print(a)

10
10


- We want to access the gloabal variable inside the function and maintaing the local variable as previous.

In [199]:
a = 33
b =90
print(id(a))
def function():
    a=10
    x = globals()['a']  #to get the particular object from the gloabal
    print(id(x))
    a=10
    print('Inside the function',a)
    
    
function()    

print(a)

1837262512
1837262512
Inside the function 10
33


so,we have got the same adddress that we had access the global to local variable.

In [203]:
a = 33
b =90
print(id(a))
def function():
    a=10
    x = globals()['a']  #to get the particular object from the gloabal
    print(id(x))
    a=10
    print('Inside the function',a)
    
    globals()['a']=20
    
function()
   

print(a)

1837262512
1837262512
Inside the function 10
20


### __main__ and __name__

- During the straing or initiating first model we usually start with command that is

In [204]:
print(__name__)

__main__


if we running the file at original then it print name as male.

But that same importetd as moudule then it will print as module name

In [208]:
def main():
    print('hello')
    print('well come user')  #This is help full get rid from the import file work
if __name__=="__main__":
    main()

hello
well come user
